"""Validates jianlik_nll against Julia's jianlik (tests/fixtures/reference_nll_jianlik.txt,
generated by scripts/gen_reference_jianlik.jl -- data generated via simq, since
Julia's simjian currently errors, see that script's comment)."""
from pathlib import Path

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import pandas as pd
import pytest

from pyem.data import _pad_by_subject
from pyem.likelihoods import jianlik_nll

FIXTURES = Path(__file__).parent / "fixtures"


def test_jianlik_matches_julia():
    df = pd.read_csv(FIXTURES / "reference_data_jianlik.csv")
    subs = sorted(df["sub"].unique())
    padded, valid_mask = _pad_by_subject(df, subs)

    with open(FIXTURES / "reference_nll_jianlik.txt") as f:
        rows = [line.strip().split(",") for line in f]

    for i, (sub, beta, nu_raw, nll_ref) in enumerate(rows):
        params = jnp.array([float(beta), float(nu_raw)])
        nll = jianlik_nll(params, padded["c"][i], padded["r"][i], valid_mask=valid_mask[i])
        assert float(nll) == pytest.approx(float(nll_ref), abs=1e-7)
