"""Validates qlik_nll against Julia's qlik at fixed, known parameters
(tests/fixtures/reference_nll.txt, generated by scripts/gen_reference_nll.jl)."""
import csv
from pathlib import Path

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import pandas as pd
import pytest

from pyem.data import _pad_by_subject
from pyem.likelihoods import qlik_nll

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="module")
def padded_data():
    df = pd.read_csv(FIXTURES / "reference_data.csv")
    subs = sorted(df["sub"].unique())
    return _pad_by_subject(df, subs)


def test_qlik_matches_julia(padded_data):
    padded, valid_mask = padded_data
    with open(FIXTURES / "reference_nll.txt") as f:
        rows = [line.strip().split(",") for line in f]

    for i, (sub, beta, lr_raw, nll_ref) in enumerate(rows):
        params = jnp.array([float(beta), float(lr_raw)])
        nll = qlik_nll(params, padded["c"][i], padded["r"][i], valid_mask=valid_mask[i])
        assert float(nll) == pytest.approx(float(nll_ref), abs=1e-8)
