"""Validates seqlik_nll against Julia's seqlik (tests/fixtures/reference_nll_seqlik.txt,
generated by scripts/gen_reference_seqlik.jl)."""
from pathlib import Path

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import pandas as pd
import pytest

from pyem.data import _pad_by_subject
from pyem.likelihoods import seqlik_nll

FIXTURES = Path(__file__).parent / "fixtures"


def test_seqlik_matches_julia():
    df = pd.read_csv(FIXTURES / "reference_data_seqlik.csv")
    subs = sorted(df["sub"].unique())
    padded, valid_mask = _pad_by_subject(df, subs, cols=("ch1", "ch2", "mn", "st"))

    with open(FIXTURES / "reference_nll_seqlik.txt") as f:
        rows = [line.strip().split(",") for line in f]

    for i, row in enumerate(rows):
        sub = row[0]
        params = jnp.array([float(v) for v in row[1:7]])
        nll_ref = float(row[7])
        nll = seqlik_nll(params, padded["ch1"][i], padded["ch2"][i], padded["mn"][i], padded["st"][i],
                          valid_mask=valid_mask[i])
        assert float(nll) == pytest.approx(nll_ref, abs=1e-7)
