"""Validates the full (dense) group-covariance path -- em_fit/emerrors/ilaplace
with a (nparam, nparam) startsigma -- against Julia's em(...; full=true)
(tests/fixtures/reference_fit_full_cov.txt, generated by
scripts/gen_reference_full_cov.jl)."""
from pathlib import Path

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import numpy as np
import pandas as pd
import pytest

from pyem.likelihoods import qlik_nll
from pyem.structs import EMModel
from pyem.emloop import em_fit
from pyem.errors import emerrors, ilaplace, lml

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="module")
def reference():
    with open(FIXTURES / "reference_fit_full_cov.txt") as f:
        ref = {}
        for line in f:
            parts = line.strip().split(",")
            ref[parts[0]] = [float(v) for v in parts[1:]]
    return ref


@pytest.fixture(scope="module")
def fitted():
    df = pd.read_csv(FIXTURES / "reference_data_full_cov.csv")
    covdf = pd.read_csv(FIXTURES / "reference_cov_full_cov.csv")
    subs = sorted(df["sub"].unique())
    cov = jnp.array(covdf.sort_values("sub")["cov"].to_numpy())
    nsub = len(subs)
    X = jnp.stack([jnp.ones(nsub), cov], axis=1)

    model = EMModel(df, X, subs=subs, likfun=qlik_nll, nparam=2)
    startbetas = jnp.array([[1.0, 0.0], [0.0, 0.0]])
    startsigma = jnp.array([1.0, 1.0])  # plain vector -- full=True expands it to a diagonal start
    fit = em_fit(model, startbetas, startsigma, emtol=1e-4, maxiter=200, full=True, quiet=0)
    return fit


def test_full_cov_dispatch(fitted):
    assert fitted.sigma.ndim == 2


def test_em_fit_matches_julia(fitted, reference):
    fit = fitted
    np.testing.assert_allclose(np.array(fit.betas.flatten()), reference["betas"], atol=1e-4)
    sigma = np.array(fit.sigma)
    np.testing.assert_allclose([sigma[0, 0], sigma[0, 1], sigma[1, 1]], reference["sigma"], atol=1e-4)


def test_emerrors_matches_julia(fitted, reference):
    errs = emerrors(fitted)
    np.testing.assert_allclose(np.array(errs.ses), reference["ses"], atol=1e-4)
    np.testing.assert_allclose(np.array(errs.pvalues), reference["pvalues"], atol=1e-4)


def test_ilaplace_matches_julia(fitted, reference):
    il = ilaplace(fitted)
    assert float(il) == pytest.approx(reference["ilaplace"][0], abs=1e-2)


def test_lml_matches_julia(fitted, reference):
    val = lml(fitted)
    assert float(val) == pytest.approx(reference["lml"][0], abs=1e-2)
