"""Validates loocv against Julia's loocv (tests/fixtures/reference_loocv.txt,
generated by scripts/gen_reference_loocv.jl -- a small NS=10 dataset since
loocv refits the model nsub times, in both Julia and here)."""
from pathlib import Path

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import numpy as np
import pandas as pd
import pytest

from pyem.likelihoods import qlik_nll
from pyem.structs import EMModel
from pyem.emloop import em_fit
from pyem.loocv import loocv

FIXTURES = Path(__file__).parent / "fixtures"


def test_loocv_matches_julia():
    df = pd.read_csv(FIXTURES / "reference_data_loocv.csv")
    covdf = pd.read_csv(FIXTURES / "reference_cov_loocv.csv")
    subs = sorted(df["sub"].unique())
    cov = jnp.array(covdf.sort_values("sub")["cov"].to_numpy())
    nsub = len(subs)
    X = jnp.stack([jnp.ones(nsub), cov], axis=1)

    with open(FIXTURES / "reference_loocv.txt") as f:
        ref = {}
        for line in f:
            parts = line.strip().split(",")
            key = parts[0]
            if key == "x":
                continue
            ref[key] = [float(v) for v in parts[1:]]

    model = EMModel(df, X, subs=subs, likfun=qlik_nll, nparam=2)
    startbetas = jnp.array([[1.0, 0.0], [0.0, 0.0]])
    startsigma = jnp.array([1.0, 1.0])
    fit = em_fit(model, startbetas, startsigma, emtol=1e-4, maxiter=200, quiet=0)
    np.testing.assert_allclose(np.array(fit.betas.flatten()), ref["betas"], atol=1e-4)
    np.testing.assert_allclose(np.array(fit.sigma), ref["sigma"], atol=1e-4)

    liks = loocv(fit, emtol=1e-3, maxiter=100, progress=False)

    np.testing.assert_allclose(np.array(liks), ref["liks"], atol=0.1)
    assert float(jnp.sum(liks)) == pytest.approx(sum(ref["liks"]), abs=0.5)
