"""Validates fit_subject (MAP + Laplace Hessian per subject) against Julia's
estep! (tests/fixtures/reference_estep.txt, generated by
scripts/gen_reference_estep.jl). Uses a fixed prior mean/covariance -- not
the true simulating parameters -- matching what the Julia reference script
does."""
from pathlib import Path

import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import pandas as pd
import pytest

from pyem.data import _pad_by_subject
from pyem.estep import fit_subject
from pyem.likelihoods import qlik_nll

FIXTURES = Path(__file__).parent / "fixtures"


def test_fit_subject_matches_julia():
    df = pd.read_csv(FIXTURES / "reference_data.csv")
    subs = sorted(df["sub"].unique())
    padded, valid_mask = _pad_by_subject(df, subs)

    betas = jnp.array([0.8, 0.1])
    sigma = jnp.diag(jnp.array([2.0, 1.5]))
    inv_sigma = jnp.linalg.inv(sigma)
    logdet_sigma = jnp.linalg.slogdet(sigma)[1]

    with open(FIXTURES / "reference_estep.txt") as f:
        ref = [line.strip().split(",") for line in f]

    for i in range(len(subs)):
        x_hat, h, l = fit_subject(betas, betas, inv_sigma, logdet_sigma,
                                   (padded["c"][i], padded["r"][i]), valid_mask[i], likfun=qlik_nll)
        sub, x1r, x2r, h11r, h12r, h22r, lr = ref[i]

        assert float(x_hat[0]) == pytest.approx(float(x1r), abs=1e-5)
        assert float(x_hat[1]) == pytest.approx(float(x2r), abs=1e-5)
        assert float(h[0, 0]) == pytest.approx(float(h11r), abs=1e-4)
        assert float(h[1, 1]) == pytest.approx(float(h22r), abs=1e-4)
        assert float(l) == pytest.approx(float(lr), abs=1e-5)
